### ISSUE TITLE
Exception on progress message

### ISSUE THREAD

**Issue by kononencheg** [Octonica/ClickHouseClient#15]
When executing a long-term selection
Clickhouse version 20.9.3.45
```
Unhandled exception. System.FormatException: One of the identified items was in an invalid format.
   at Octonica.ClickHouseClient.ClickHouseBinaryProtocolReader.Read7BitInt32(Boolean async, CancellationToken cancellationToken)
   at Octonica.ClickHouseClient.Protocol.ServerProgressMessage.Read(ClickHouseBinaryProtocolReader reader, Boolean async, CancellationToken cancellationToken)
   at Octonica.ClickHouseClient.ClickHouseBinaryProtocolReader.ReadMessage(Boolean throwOnUnknownMessage, Boolean async, CancellationToken cancellationToken)
   at Octonica.ClickHouseClient.ClickHouseTcpClient.Session.WithCancellationToken[T](CancellationToken token, Func`2 execute)
   at Octonica.ClickHouseClient.ClickHouseTcpClient.Session.ReadMessage(Boolean async, CancellationToken cancellationToken)
   at Octonica.ClickHouseClient.ClickHouseDataReader.Read(Boolean nextResult, Boolean async, CancellationToken cancellationToken)
   at Octonica.ClickHouseClient.ClickHouseDataReader.Read(Boolean nextResult, Boolean async, CancellationToken cancellationToken)
...
 ```

**Comment by victor-sushko** [comment]
@kononencheg
Thank you for bug report! The bug was fixed in the release v1.0.17.
