### ISSUE TITLE
Date32 value 1925-01-01 read as 0001-01-01

### ISSUE THREAD

**Issue by MaceWindu** [Octonica/ClickHouseClient#60]
```sql
CREATE TABLE IF NOT EXISTS TypeTable
(
	Id             Int32  NOT NULL,
	Column         Date32 NOT NULL,
)
ENGINE = Memory()

INSERT INTO TypeTable
(
	Id,
	Column
)
VALUES
(toInt32(1),toDate32('1925-01-01'))
```

Data reader's `GetValue`/`GetDate` method returns default value `0001-01-01` instead of actual value from table.
Works fine for max-value (`2283-11-11`).

**Comment by MaceWindu** [comment]
Tested DateTime64:
```
System.OverflowException
  Message=The value 0xFFCD8C88F2850000 is greater than the maximal value of the type "System.DateTime". It is only possible to read this value as "System.UInt64".
  StackTrace:
   at Octonica.ClickHouseClient.Types.DateTime64TableColumn.GetValue(Int32 index)
   at Octonica.ClickHouseClient.Types.ReinterpretedTableColumn`2.GetValue(Int32 index)
   at Octonica.ClickHouseClient.ClickHouseDataReader.GetFieldValue[T](Int32 ordinal)
```

**Comment by Alex69rus** [comment]
I don't get `DateTime.MinValue` value while fetching `DateTime64` fields with value less than `1970-01-01`, but I get exception:
```
Octonica.ClickHouseClient.Exceptions.ClickHouseHandledException
The value must be in range [1970-01-01T00:00:00.0000000+00:00, 9999-12-31T23:59:59.9999999+00:00].
```

```sql
CREATE TABLE IF NOT EXISTS TypeTable
(
    Id            Int32,
    Column  DateTime64
)
    ENGINE = Memory();

INSERT INTO TypeTable (Id, Column) VALUES (1, toDateTime64('1925-01-01', 3));
```

Fetching code:
```csharp
public class TypeTable
{
    int            Id     { get; set; }
    DateTimeOffset Column { get; set; }
}

var result = await _connection.QueryFirstOrDefaultAsync<TypeTable>("SELECT * FROM TypeTable");
```

**Comment by Alex69rus** [comment]
Also there is a problem with filtering by DateTime64 values:
```csharp
var result = await _connection.QueryFirstOrDefaultAsync<TypeTable>(
    new CommandDefinition(
      "SELECT * FROM TypeTable WHERE Column > {DateTimeFilter:DateTime64}",
      new Dictionary<string, object>
      {
          { "DateTimeFilter", new DateTimeOffset(1930, 1, 1, 1, 1, 1, TimeSpan.Zero) }
      }
  )
);
```

Exception:
```
Octonica.ClickHouseClient.Exceptions.ClickHouseHandledException
The value must be in range [1970-01-01 00:00:00, 2105-12-31 23:59:59].
```
